In [2]:
## DISCLAIMER  , I'M USING THIS FILE MOSTLY FOR Testing purpose



import implementations
import pandas as pd
import numpy as np
import helpers



## SEE THIS : https://github.com/byrek3d/ML-Project-1-EPFL/blob/master/run.ipynb







In [9]:
## TODO DELETE , pandas isn't allowed , just here for exploratory data annalysis 

x = pd.read_csv("./dataset/x_train.csv",sep=',')


x.head()



Id  _STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0   0      53      11  11162015      11    16   2015      1100  2015015629   
1   1      33      12  12152015      12    15   2015      1200  2015004387   
2   2      20      10  10202015      10    20   2015      1100  2015005638   
3   3      42       6   6182015       6    18   2015      1100  2015004694   
4   4      24      11  11062015      11     6   2015      1100  2015004673   

         _PSU  ...  _PAREC1  _PASTAE1  _LMTACT1  _LMTWRK1  _LMTSCL1  _RFSEAT2  \
0  2015015629  ...        1         1       3.0       3.0       4.0         1   
1  2015004387  ...        9         9       3.0       3.0       4.0         9   
2  2015005638  ...        4         2       2.0       2.0       3.0         1   
3  2015004694  ...        2         2       2.0       2.0       3.0         1   
4  2015004673  ...        9         9       3.0       3.0       4.0         1   

   _RFSEAT3  _FLSHOT6  _PNEUMO2  _AIDTST3  
0         1       NaN       NaN       2.0  
1         9       NaN       NaN       NaN  
2         1       1.0       2.0       2.0  
3         1       2.0       2.0       2.0  
4         1       9.0       9.0       2.0  

[5 rows x 322 columns]

In [74]:
x["CTELENUM"]

0         NaN
1         1.0
2         1.0
3         NaN
4         1.0
         ... 
328130    NaN
328131    NaN
328132    1.0
328133    1.0
328134    1.0
Name: CTELENUM, Length: 328135, dtype: float64

In [75]:
numbers = [0, 0, 3, 0, 5, 0, 7]

non_zero_indices = [index for index, value in enumerate(numbers) if value != 0]

print(non_zero_indices)

[2, 4, 6]


In [73]:
for column_name in x.columns:
    print(column_name)


Id
_STATE
FMONTH
IDATE
IMONTH
IDAY
IYEAR
DISPCODE
SEQNO
_PSU
CTELENUM
PVTRESD1
COLGHOUS
STATERES
CELLFON3
LADULT
NUMADULT
NUMMEN
NUMWOMEN
CTELNUM1
CELLFON2
CADULT
PVTRESD2
CCLGHOUS
CSTATE
LANDLINE
HHADULT
GENHLTH
PHYSHLTH
MENTHLTH
POORHLTH
HLTHPLN1
PERSDOC2
MEDCOST
CHECKUP1
BPHIGH4
BPMEDS
BLOODCHO
CHOLCHK
TOLDHI2
CVDSTRK3
ASTHMA3
ASTHNOW
CHCSCNCR
CHCOCNCR
CHCCOPD1
HAVARTH3
ADDEPEV2
CHCKIDNY
DIABETE3
DIABAGE2
SEX
MARITAL
EDUCA
RENTHOM1
NUMHHOL2
NUMPHON2
CPDEMO1
VETERAN3
EMPLOY1
CHILDREN
INCOME2
INTERNET
WEIGHT2
HEIGHT3
PREGNANT
QLACTLM2
USEEQUIP
BLIND
DECIDE
DIFFWALK
DIFFDRES
DIFFALON
SMOKE100
SMOKDAY2
STOPSMK2
LASTSMK2
USENOW3
ALCDAY5
AVEDRNK2
DRNK3GE5
MAXDRNKS
FRUITJU1
FRUIT1
FVBEANS
FVGREEN
FVORANG
VEGETAB1
EXERANY2
EXRACT11
EXEROFT1
EXERHMM1
EXRACT21
EXEROFT2
EXERHMM2
STRENGTH
LMTJOIN3
ARTHDIS2
ARTHSOCL
JOINPAIN
SEATBELT
FLUSHOT6
FLSHTMY2
IMFVPLAC
PNEUVAC3
HIVTST6
HIVTSTD3
WHRTST10
PDIABTST
PREDIAB1
INSULIN
BLDSUGAR
FEETCHK2
DOCTDIAB
CHKHEMO3
FEETCHK
EYEEXAM
DIABEYE
DIABEDU
CAREGIV1

In [8]:
max(x["_STATE"])

72

In [5]:
# My project folder contain a folder called "dataset". I can't push it to github since it's too big

datapath = "./dataset/"


x_train, x_test, y_train, train_ids, test_ids = helpers.load_csv_data(datapath)

In [6]:
N = x_train.shape[0]
D = x_train.shape[1]
N,D

(328135, 321)

In [13]:
tab = []

for i in range(D):

    count = 0
    for j in range(N):
        if np.isnan(x_train[j][i]):
            count = count+1
        
    tab.append(count/N*100.)
    


print(tab)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 42.48708610785195, 42.48708610785195, 99.99024791625398, 42.48739086046901, 42.48708610785195, 99.99024791625398, 42.492571654959086, 42.52030414311183, 42.52060889572889, 57.512913892148056, 57.512913892148056, 57.513218644765104, 57.512913892148056, 99.75589315373246, 57.51260913953099, 57.68570862602282, 58.67828789979734, 0.000609505234126198, 0.000304752617063099, 0.0, 48.71775336370701, 0.0, 0.0, 0.000304752617063099, 0.000304752617063099, 0.000304752617063099, 59.833300318466485, 0.0, 13.348469379980802, 13.348469379980802, 0.0, 0.0, 86.59637039633078, 0.000304752617063099, 0.0, 0.0, 0.000304752617063099, 0.0, 0.0, 0.0015237630853154951, 87.13334450759595, 0.0, 0.0, 0.0, 0.0, 42.48708610785195, 96.98599661724595, 42.48708610785195, 0.000304752617063099, 0.0, 0.000914257851189297, 0.7530437167629177, 0.9773416429213586, 1.2025538269309888, 1.3430447833970773, 85.22803114571747, 2.1128498940984657, 2.3596995139195758, 2.527313453304280

In [5]:
# TODO DATA PREPRECOSSING : REMOVE CATEGORICAL DATA 
"""
            CALCULATED VARIABLE 



 _RFHLTH :  HEALTH STATUS
            1 : Good or Better Health
            2 : Fair or Poor Health 
            9 : Don't know , Missing 

_HCVU651 :
        1 Have Health care coverage 
        2 Do not have health care covergae
        3 Don't know/missing 





"""


"\n            CALCULATED VARIABLE \n\n\n\n _RFHLTH :  HEALTH STATUS\n            1 : Good or Better Health\n            2 : Fair or Poor Health \n            9 : Don't know , Missing \n\n_HCVU651 :\n        1 Have Health care coverage \n        2 Do not have health care covergae\n        3 Don't know/missing \n\n\n\n\n\n"

In [15]:


initial_w = np.zeros(D) 
print(initial_w)
## Todo better initialization ? maybe normal distributed
MaxIter = 100000
gamma = 0.01

w,loss = implementations.logistic_regression(y_train, x_train, initial_w, MaxIter, gamma)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0.]
uwu
w :  [nan nan nan 

KeyboardInterrupt: 

In [44]:

# REMOVE FROM X_train and X_Test All collumns that contains Nan ( this is a bit drastic , we're losing a lot of information)

ind = (np.arange(0,D))



x_train_with_index = np.vstack([ind,x_train])


x_train2_with_index = x_train_with_index[:, ~np.isnan(x_train_with_index).any(axis=0)]


indexestokeep = x_train2_with_index[0].astype(int)



indexToDROP = [index for index in ind if index not in indexestokeep]


x_test2=np.delete(x_test,indexToDROP,axis=1)
x_train2 = np.delete(x_train,indexToDROP,axis=1)




print(x_test2.shape,x_train2.shape)

(109379, 82) (328135, 82)


In [54]:
## TODO THIS IS NOT ALLOWED , JUST FOR TESTING 

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train2,y_train)

y_pred = knn.predict(x_test2)


print(y_pred)

[-1 -1 -1 ...  1 -1 -1]


In [47]:
for a in y_pred:
    print(a)

-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-

In [55]:
helpers.create_csv_submission(test_ids, y_pred, "Submission.csv")

In [29]:
a = np.array([1,2,3,4,9,1,2,10,2])


def one_hot_encoding_special(collumn,num_max,skip):

    collumn_as_int = collumn.astype(int)
    num_classes = num_max
    print("num_class , :",num_classes)
    collumn_as_int[np.isin(collumn_as_int, skip)]=0
    print(collumn_as_int)
    
    result = np.eye(num_classes)[collumn_as_int]
    
    return result

encode = one_hot_encoding_special(a,6,[9,10])



num_class , : 6
[1 2 3 4 0 1 2 0 2]
[1. 0. 0. 0. 0. 1. 0. 0. 0.]


In [23]:
a = np.array([1,2,3,4,9,1,2,10,2])


def one_hot_encoding(collumn):
    int_coll = collumn.astype(int)
    num_classes = max(int_coll)+1
    print("num_class , :",num_classes)
    result = np.eye(num_classes)[int_coll]
    
    return result

one_hot_encoding(a).shape

num_class , : 11


(9, 11)

In [18]:
import numpy as np

# Create your NumPy array (replace this with your actual array)
original_array = np.array([1, 9, 5, 9, 3, 2, 9, 7, 10, 2, 3, 9, 4, 10, 3])

# Define the values to be mapped to 0
values_to_map_to_0 = [9, 10]

# Create a new array by copying the original array

# Use boolean indexing to set elements in the original array equal to the values in values_to_map_to_0 to 0
original_array[np.isin(original_array, values_to_map_to_0)] = 0

# Print the transformed array
print(transformed_array)

[1 0 5 0 3 2 0 7 0 2 3 0 4 0 3]


In [30]:
collumn_to_oneHotencode_special = [("MARITAL",6,[9]),("EDUCA",6,[9]),("RENTHOM1",3,[7,9]),("EMPLOY1",8,[9])]


for a,b,c in collumn_to_oneHotencode_special:
    print("a : ",a)
    print("b : ",b)
    print("c : ",c)

a :  MARITAL
b :  6
c :  [9]
a :  EDUCA
b :  6
c :  [9]
a :  RENTHOM1
b :  3
c :  [7, 9]
a :  EMPLOY1
b :  8
c :  [9]


In [44]:
#type(x[x["INCOME2"].isna()]["INCOME2"][24])

a = np.array([1.,2.,4,231.,float('nan')])

a.astype(int)

/var/folders/9_/z1m27wy57j34pk1k36dtbd280000gn/T/ipykernel_7715/1977067696.py:5: RuntimeWarning: invalid value encountered in cast
  a.astype(int)


array([  1,   2,   4, 231,   0])

In [45]:
x["WEIGHT2"]

0          110.0
1          200.0
2         9999.0
3          168.0
4          190.0
           ...  
328130     177.0
328131     170.0
328132     320.0
328133     250.0
328134     150.0
Name: WEIGHT2, Length: 328135, dtype: float64

In [67]:
100 * x[x["_VEG23"].isna()].shape[0]/x.shape[0] 

0.0

In [77]:
x["CHOLCHK"]

0         1
1         1
2         1
3         2
4         1
         ..
328130    1
328131    9
328132    1
328133    1
328134    1
Name: _CHOLCHK, Length: 328135, dtype: int64